config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/itwinai:
      branch: main
      repo: https://github.com/interTwin-eu/itwinai
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.viridian_confused_cougar.sh
        container: qc.acc_wine_responsible_mongoose
  QC.Doc:
    repos:
      github.com/interTwin-eu/itwinai find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.reef_witty_python.sh
        container: qc.doc_aquamarine_timid_rattlesnake
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.denim_proactive_tapir.sh
        container: qc.doc_viridian_humorous_rhinoceros
      github.com/interTwin-eu/itwinai markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.plum_meticulous_grizzly.sh
        container: qc.doc_grape_sociable_koala
      github.com/interTwin-eu/itwinai restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_outgoing_beaver.sh
        container: qc.doc_puce_perky_dugong
  QC.Lic:
    repos:
      github.com/interTwin-eu/itwinai licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bone_vibrant_spren.sh
        container: qc.lic_pumpkin_elated_gorilla
  QC.Met:
    repos:
      github.com/interTwin-eu/itwinai cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crimson_brave_angelfish.sh
        container: qc.met_silver_bewildered_llama
  QC.Sec:
    repos:
      github.com/interTwin-eu/itwinai bandit:
        commands:
        - /usr/bin/env sh .sqa/script.amaranth_philosophical_kangaroo.sh
        container: qc.sec_moss_inventive_marmoset
  QC.Sty:
    repos:
      github.com/interTwin-eu/itwinai flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fern_friendly_turkey.sh
        container: qc.sty_snow_exuberant_iguana
      github.com/interTwin-eu/itwinai hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cosmos_brave_cassowary.sh
        container: qc.sty_ultramarine_bubbly_dhole
      github.com/interTwin-eu/itwinai jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jade_bright_walrus.sh
        container: qc.sty_butterscotch_lucky_catfish
      github.com/interTwin-eu/itwinai pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_mature_emu.sh
        container: qc.sty_banana_passionate_octopus
  QC.Uni:
    repos:
      github.com/interTwin-eu/itwinai pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ivory_devoted_opossum.sh
        container: qc.uni_rosewater_innocent_crane
  QC.Ver:
    repos:
      github.com/interTwin-eu/itwinai get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.white_wondrous_raccoon.sh
        container: qc.ver_wave_fair_caribou
timeout: 5400
