config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/itwinai:
      branch: main
      repo: https://github.com/interTwin-eu/itwinai
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.ecru_wise_marmoset.sh
        container: qc.acc_byzantium_lively_owl
  QC.Doc:
    repos:
      github.com/interTwin-eu/itwinai find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.olive_attentive_walrus.sh
        container: qc.doc_daffodil_sad_wolverine
      github.com/interTwin-eu/itwinai git:
        commands:
        - /usr/bin/env sh .sqa/script.mustard_whimsical_pelican.sh
        container: qc.doc_cosmos_inspired_capybara
      github.com/interTwin-eu/itwinai markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.coral_grateful_kangaroo.sh
        container: qc.doc_marigold_calm_bear
      github.com/interTwin-eu/itwinai restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.paprika_romantic_newt.sh
        container: qc.doc_maroon_independent_gazelle
  QC.Lic:
    repos:
      github.com/interTwin-eu/itwinai licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_adventurous_chipmunk.sh
        container: qc.lic_orchid_independent_dormouse
  QC.Met:
    repos:
      github.com/interTwin-eu/itwinai cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.raspberry_forgiving_tiger.sh
        container: qc.met_marina_focused_reindeer
  QC.Sec:
    repos:
      github.com/interTwin-eu/itwinai bandit:
        commands:
        - /usr/bin/env sh .sqa/script.green_careful_griffin.sh
        container: qc.sec_dawn_restless_lynx
  QC.Sty:
    repos:
      github.com/interTwin-eu/itwinai flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_savvy_gull.sh
        container: qc.sty_sunset_gracious_armadillo
      github.com/interTwin-eu/itwinai hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_attentive_thrush.sh
        container: qc.sty_ecru_warm_axolotl
      github.com/interTwin-eu/itwinai jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.mustard_stoic_turkey.sh
        container: qc.sty_tan_clever_hare
      github.com/interTwin-eu/itwinai pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.pink_easygoing_iguana.sh
        container: qc.sty_clove_sociable_nymph
  QC.Uni:
    repos:
      github.com/interTwin-eu/itwinai commands:
        commands:
        - /usr/bin/env sh .sqa/script.seafoam_helpful_lemur.sh
        container: qc.uni_bone_dedicated_boar
  QC.Ver:
    repos:
      github.com/interTwin-eu/itwinai get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fog_determined_jaguar.sh
        container: qc.ver_orange_thoughtful_finch
timeout: 5400
